//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAwebApp.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr_BE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr_BE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QAwebApp.Locales.Resources.fr-BE", typeof(Resources_fr_BE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un Bug.
        /// </summary>
        internal static string create_bug {
            get {
                return ResourceManager.GetString("create.bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        internal static string create_project {
            get {
                return ResourceManager.GetString("create.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau projet.
        /// </summary>
        internal static string create_project_tooltip {
            get {
                return ResourceManager.GetString("create.project.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers existants.
        /// </summary>
        internal static string files_existingfiles {
            get {
                return ResourceManager.GetString("files.existingfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de fichiers.
        /// </summary>
        internal static string files_nofiles {
            get {
                return ResourceManager.GetString("files.nofiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun fichier n&apos;a été téléchargé..
        /// </summary>
        internal static string files_notexistingfiles {
            get {
                return ResourceManager.GetString("files.notexistingfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exigences.
        /// </summary>
        internal static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cas de test.
        /// </summary>
        internal static string TestCases {
            get {
                return ResourceManager.GetString("TestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécution des tests.
        /// </summary>
        internal static string TestExecutions {
            get {
                return ResourceManager.GetString("TestExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans de tests.
        /// </summary>
        internal static string TestPlans {
            get {
                return ResourceManager.GetString("TestPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests existants.
        /// </summary>
        internal static string tests_existingtests {
            get {
                return ResourceManager.GetString("tests.existingtests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de tests.
        /// </summary>
        internal static string tests_notests {
            get {
                return ResourceManager.GetString("tests.notests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir le profil.
        /// </summary>
        internal static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
